apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keystone-token-secret-writer
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]