apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keystone-token-secret-binding
  namespace: external-secrets
subjects:
  - kind: ServiceAccount
    name: keystone-token-job
    namespace: external-secrets
roleRef:
  kind: Role
  name: keystone-token-secret-writer
  apiGroup: rbac.authorization.k8s.io
