apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-keystone-token-job
  namespace: external-secrets
spec:
  schedule: "*/30 * * * *"  # every 30 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: keystone-token-job
          containers:
            - name: token-rotator
              image: python:3.11-slim
              command:
              - /bin/sh
              - -c
              - |
                pip install requests kubernetes && python /app/update_keystone_secret.py
              envFrom:
                - secretRef:
                    name: os-application-credentials
              volumeMounts:
                - name: update-keystone-script
                  mountPath: /app
          restartPolicy: OnFailure
          volumes:
            - name: update-keystone-script
              configMap:
                name: update-keystone-secret-script