apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mswa-prod
  namespace: argocd
spec:
  destination:
    namespace: mswa-prod
    server: https://kubernetes.default.svc
  source:
    path: app
    repoURL: https://github.com/Mobility-Scooter-Project/mobility-scooter-infa
    targetRevision: bryan/tri-env-setup
    helm:
      valueFiles:
        - values-prod.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
