---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: develop
  namespace: mswa
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: dev-warehouse
      sources:
        direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: mswa
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: prod-warehouse
      sources:
        direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: mswa
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: prod-warehouse
      sources:
        stages:
          - uat