apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devpod-role
  namespace: devpod
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "pods/log"
      - "pods/exec" 
      - "pods/attach"
      - "persistentvolumeclaims"
      - "persistentvolumes"
      - "serviceaccounts"
      - "secrets"
      - "configmaps"
      - "services"
      - "endpoints"
      - "events"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "replicasets"
      - "statefulsets"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - "networkpolicies"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]