apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-argocd-gh-secret
  namespace: argocd
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: argocd-gh
    template:
      engineVersion: v2
      data:
        githubAppID: "{{ .ARGOCD_GH_APP_ID }}"
        githubAppInstallationID: "{{ .ARGOCD_GH_APP_INSTALLATION_ID }}"
        githubAppPrivateKey: "{{ .ARGOCD_GH_APP_PRIVATE_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: ARGOCD_GH_.*