apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ghexternalsecret.yaml
  - applicationset.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/manifests/install.yaml