apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-oauth2-proxy-config
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: oauth2-proxy-config
    template:
      engineVersion: v2
      templateFrom:
        - target: Annotations
          literal: |
            secret-generator.v1.mittwald.de/autogenerate: cookie-secret
            secret-generator.v1.mittwald.de/length: "32"
      data:
        client-id: "{{ .OAUTH2_GH_CLIENT_ID }}"
        client-secret: "{{ .OAUTH2_GH_CLIENT_SECRET }}"
  dataFrom:
    - find:
        name:
          regexp: OAUTH2_GH_*