apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-oauth2-proxy-config
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: oauth2-proxy-config
  dataFrom:
    - find:
        name:
          regexp: oauth2-proxy-config