apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-headers
  namespace: oauth2-proxy
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: oauth.cis240470.projects.jetstream-cloud.org
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true