apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 7.17.1
    helm:
      releaseName: oauth2-proxy
      fileParameters:
        - name: config.configFile
          path: ./oauth2-proxy.cfg
  destination:
    server: "https://kubernetes.default.svc"
    namespace: oauth2-proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
