apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: github
spec:
  provider:
    # provider type: github
    github:
      appID: 1169322
      auth:
        privateKey:
          name: gh-private-key
          key: GH_PRIVATE_KEY
      installationID: 77185039
      organization: "Mobility-Scooter-Project"
      repository: "mobility-scooter-web-infra"
      #environment: "Optional. set this for environment secrets"
