apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # include the bootstrap overlay to allow argocd to be patched by overlays
  - ../bootstrap
  - external-dns/namespace.yaml
  - external-secrets
  - cert-manager
  - cnpg
  - ../helm
  - infisical
  - argocd
  - devpod
  - rbac
