apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  # The name of this "recipe" resource
  name: pg-connection-string
spec:
  # This is the name of the NEW secret that ESO will create for Infisical
  target:
    name: pg-connection-string-secret
    # The 'template' block is where the magic happens
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://app:{{ .password | urlquery }}@pgcluster-rw.default.svc.cluster.local:5432"

  # This points to the SecretStore we defined above
  secretStoreRef:
    name: local-secret-store
    kind: ClusterSecretStore

  # This defines the SOURCE of the data
  dataFrom:
    - extract:
        # The name of the EXISTING secret created by your database
        key: pgcluster-secret
