apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecret
  namespace: argocd
spec:
  project: default
  source:
    chart: cluster-secret
    repoURL: https://charts.clustersecret.com
    targetRevision: 0.4.3
    helm:
      releaseName: clustersecret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: clustersecret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true