apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvdp
  namespace: argocd
spec:
  project: default
  source:
    chart: nvidia-device-plugin
    repoURL: https://nvidia.github.io/k8s-device-plugin
    targetRevision: 0.17.3
    helm:
      releaseName: nvdp
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nvdp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

# See https://github.com/NVIDIA/k8s-device-plugin#quick-start for more details.