apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
spec:
  project: default
  source:
    chart: kubernetes-secret-generator
    repoURL: https://helm.mittwald.de
    targetRevision: 3.4.0
    helm:
      releaseName: secret-generator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: secret-generator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
