apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
spec:
  project: default
  source:
    chart: valkey
    repoURL:  https://charts.bitnami.com/bitnami
    targetRevision: 3.0.22
    helm:
      releaseName: valkey
  destination:
    server: "https://kubernetes.default.svc"
    namespace: valkey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true