apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  {{- if .Values.database.enabled }}
  {{ .Values.database.connectionStringEnvVarName }}: >
    postgres://app:${DB_PASSWORD}@pgcluster-rw.default.svc.cluster.local:5432/{{ .Values.database.name }}
  {{- end }}
  {{- if .Values.kv.enabled }}
  {{ .Values.kv.connectionStringEnvVarName }}: "redis://valkey-primary.valkey.svc.cluster.local:6379"
  {{- end }}
  {{- if .Values.queue.enabled }}
  {{ .Values.queue.connectionStringEnvVarName }}: "http://redpanda:9092"
  {{- end }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}