apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - system.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - ghexternalsecret.yaml
  - runner.yaml
  - storageclass.yaml
