apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: default
  source:
    chart: gha-runner-scale-set
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
    helm:
      releaseName: arc-runner-set
      values: |
        githubConfigUrl: "https://github.com/Mobility-Scooter-Project"
        githubConfigSecret: arc-gh
        controllerServiceAccount:
          name: arc-gha-rs-controller
          namespace: arc-systems
        minRunners: 1
        maxRunners: 3
        scaleSetName: "arc-runner-set"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
