apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: {{ .Values.redis.service.type }}
