apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: AUTH_SECRET, ENCRYPTION_KEY
type: Opaque
stringData:
  SITE_URL: https://localhost