apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-overrides
  namespace: infisical
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  target:
    name: infisical-backend
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_URI: "{{ .DATABASE_URL }}"
        REDIS_URL: "redis://valkey-primary.valkey.svc.cluster.local:6379"
        SITE_URL: "https://infisical.cis240470.projects.jetstream-cloud.org"

  secretStoreRef:
    name: local-secret-store
    kind: ClusterSecretStore

  dataFrom:
    - extract:
        key: pg-connection-string-secret