apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-gh-secret
  namespace: infisical
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  target:
    name: infisical-backend
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        CLIENT_ID_GITHUB_LOGIN: "{{ .GH_CLIENT_ID }}"
        CLIENT_SECRET_GITHUB_LOGIN: "{{ .GH_CLIENT_SECRET }}"

  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore

  dataFrom:
    - find:
        name:
          regexp: GH_.*
