apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: swift-output
  namespace: logging
spec:
  s3:
    s3_endpoint: https://js2.jetstream-cloud.org:8001
    s3_bucket: msp-cluster-prod-logs
    aws_key_id:
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: awsAccessKeyID
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          name: s3-secret
          key: awsSecretAccessKey
    force_path_style: "true"
    path: logs/${tag}/%Y/%m/%d/