apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-s3-secret
  namespace: logging
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: s3-secret
    template:
      engineVersion: v2
      data:
        awsAccessKeyID: "{{ .AWS_ACCESS_KEY_ID }}"
        awsSecretAccessKey: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: AWS_.*