{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgconnectionstring-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
stringData:
  connectionString: |
    {{- $sec := lookup "v1" "Secret" "default" "pgcluster-secret" }}
    {{- if $sec }}
      {{- $pw := $sec.data.password | b64dec }}
      {{- $enc := $pw | urlquery }}
      postgres://app:{{ $enc }}@pgcluster-rw.default.svc.cluster.local:5432/{{ .Values.database.name }}
    {{- else }}
      postgres://app:default-password@pgcluster-rw.default.svc.cluster.local:5432/{{ .Values.database.name }}
    {{- end }}
{{- end }}