{{- if .Values.database.enabled }}
{{- $sec := lookup "v1" "Secret" "default" "pgcluster-secret" }}
{{- if $sec }}
apiVersion: v1
kind: Secret
metadata:
  name: pgconnectionstring-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  connectionString: {{ printf "postgres://app:%s@pgcluster-rw.default.svc.cluster.local:5432/%s" ($sec.data.password | b64dec | urlquery) .Values.database.name | b64enc }}
{{- else }}
# Secret pgcluster-secret not found - skipping connection string creation
# This will be created when the secret becomes available
{{- end }}
{{- end }}