name: api

replicas: 1
image:
  repository: myrepository
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

queue:
  enabled: false
  connectionStringEnvVarName: QUEUE_CONNECTION_STRING

service:
  port: 3000
  targetPort: 3000