apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  namespace: oauth2-proxy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: oauth.cis240470.projects.jetstream-cloud.org
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-oauth-headers@kubernetescrd
spec:
  ingressClassName: traefik
  #tls:
  # - hosts:
  #    - argocd.cis240470.projects.jetstream-cloud.org
  # secretName: argocd-tls
  rules:
    - host: oauth.cis240470.projects.jetstream-cloud.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80
