apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy-ingress
  namespace: oauth2-proxy
  annotations:
    external-dns.alpha.kubernetes.io/hostname: oauth.cis240470.projects.jetstream-cloud.org
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: oauth2-proxy-oauth-headers@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #cert-manager.io/acme-challenge-type: http01
spec:
  ingressClassName: traefik
  tls:
   - hosts:
      - oauth.cis240470.projects.jetstream-cloud.org
     secretName: oauth-tls
  rules:
    - host: oauth.cis240470.projects.jetstream-cloud.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 80
